// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuztodntjoskejgxlaib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1enRvZG50am9za2VqZ3hsYWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDMxMzQsImV4cCI6MjA3MjM3OTEzNH0.-NLzNoBU4YpJglVstLHqPJ31FJkKKM5PiDIthlAug0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});